---

- name: "Clean up temporary inventory dir"
  debug:
    msg: "{{ item }}"
#  file:
#    path: "{{ item }}"
#    state: absent
  with_items:
  - "{{ tmp_inv_dir }}"

- name: "Clean up temporary dependency dir"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ tmp_dep_dir }}"
